### ISSUE TITLE
Error on docker compose up

### ISSUE THREAD

**Issue by gabazureus** [larsbaunwall/bricky#4]
Hello!

First of all, awesome project! Thank you!

I have created an .env file inside the "api" directory with this configuration
![image](https://user-images.githubusercontent.com/5619673/218107965-d1dafa09-5f99-45ae-a1e5-40e69d1573ae.png)

And then I enter in the api folder, and tried to run "docker compose up", and got these errors:
```
$ sudo docker compose up
[+] Running 2/0
 ⠿ Container bricky-app-1  Created                                                                                    0.0s
 ⠿ Container bricky-api-1  Created                                                                                    0.0s
Attaching to bricky-api-1, bricky-app-1
bricky-app-1  | 
bricky-app-1  | > bricky-chat@0.1.0 start
bricky-app-1  | > next start
bricky-app-1  | 
bricky-app-1  | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
bricky-api-1  | INFO:haystack.telemetry:Telemetry has been disabled.
bricky-api-1  | DEBUG:haystack.pipelines.base:Running node 'File` with input: {'root_node': 'File', 'params': None, 'node_id': 'File'}
bricky-api-1  | DEBUG:haystack.pipelines.base:Running node 'MarkdownConverter` with input: {'root_node': 'File', 'params': {}, 'node_id': 'MarkdownConverter'}
bricky-api-1  | DEBUG:haystack.pipelines.base:Exception while running node 'MarkdownConverter' with input {'root_node': 'File', 'params': {}, 'node_id': 'MarkdownConverter'}
bricky-api-1  | Traceback (most recent call last):
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/haystack/pipelines/base.py", line 530, in run
bricky-api-1  |     node_output, stream_id = self._run_node(node_id, node_input)
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/haystack/pipelines/base.py", line 457, in _run_node
bricky-api-1  |     return self.graph.nodes[node_id]["component"]._dispatch_run(**node_input)
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/haystack/nodes/base.py", line 201, in _dispatch_run
bricky-api-1  |     return self._dispatch_run_general(self.run, **kwargs)
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/haystack/nodes/base.py", line 245, in _dispatch_run_general
bricky-api-1  |     output, stream = run_method(**run_inputs, **run_params)
bricky-api-1  | TypeError: BaseConverter.run() missing 1 required positional argument: 'file_paths'
bricky-api-1  | 
bricky-api-1  | The above exception was the direct cause of the following exception:
bricky-api-1  | 
bricky-api-1  | Traceback (most recent call last):
bricky-api-1  |   File "/opt/venv/bin/uvicorn", line 8, in <module>
bricky-api-1  |     sys.exit(main())
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
bricky-api-1  |     return self.main(*args, **kwargs)
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
bricky-api-1  |     rv = self.invoke(ctx)
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
bricky-api-1  |     return ctx.invoke(self.callback, **ctx.params)
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
bricky-api-1  |     return __callback(*args, **kwargs)
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/uvicorn/main.py", line 404, in main
bricky-api-1  |     run(
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/uvicorn/main.py", line 569, in run
bricky-api-1  |     server.run()
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
bricky-api-1  |     return asyncio.run(self.serve(sockets=sockets))
bricky-api-1  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
bricky-api-1  |     return loop.run_until_complete(main)
bricky-api-1  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
bricky-api-1  |     return future.result()
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
bricky-api-1  |     config.load()
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/uvicorn/config.py", line 477, in load
bricky-api-1  |     self.loaded_app = import_from_string(self.app)
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
bricky-api-1  |     module = importlib.import_module(module_str)
bricky-api-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
bricky-api-1  |     return _bootstrap._gcd_import(name[level:], package, level)
bricky-api-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
bricky-api-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
bricky-api-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
bricky-api-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
bricky-api-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
bricky-api-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
bricky-api-1  |   File "/home/appuser/./main.py", line 28, in <module>
bricky-api-1  |     index_pipe.ensure_index()
bricky-api-1  |   File "/home/appuser/./pipelines/indexing.py", line 57, in ensure_index
bricky-api-1  |     self.pipeline.run(file_paths=files_to_index)
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/haystack/pipelines/base.py", line 535, in run
bricky-api-1  |     raise Exception(
bricky-api-1  | Exception: Exception while running node 'MarkdownConverter': BaseConverter.run() missing 1 required positional argument: 'file_paths'
bricky-api-1  | Enable debug logging to see the data that was passed when the pipeline failed.
bricky-api-1 exited with code 1
```

I can access localhost:3000, but I get this error when I do:

```
bricky-app-1  | Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
bricky-app-1  | Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
bricky-app-1  | TypeError: fetch failed
bricky-app-1  |     at Object.fetch (node:internal/deps/undici/undici:14152:11)
bricky-app-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
bricky-app-1  |     at async __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/chat.js:16:22)
bricky-app-1  |     at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:363:9)
bricky-app-1  |     at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:487:9)
bricky-app-1  |     at async Object.fn (/app/node_modules/next/dist/server/next-server.js:749:37)
bricky-app-1  |     at async Router.execute (/app/node_modules/next/dist/server/router.js:253:36)
bricky-app-1  |     at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:384:29)
bricky-app-1  |     at async NextNodeServer.handleRequest (/app/node_modules/next/dist/server/base-server.js:322:20) {
bricky-app-1  |   cause: Error: getaddrinfo EAI_AGAIN api
bricky-app-1  |       at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
bricky-app-1  |     errno: -3001,
bricky-app-1  |     code: 'EAI_AGAIN',
bricky-app-1  |     syscall: 'getaddrinfo',
bricky-app-1  |     hostname: 'api'
bricky-app-1  |   }
bricky-app-1  | }
```

I can't access localhost:8000/docs

Am I doing something wrong?
Thanks!

**Comment by gabazureus** [comment]
I have a doubt, in my doc dir I can put what kind of files?

**Comment by larsbaunwall** [comment]
Hi @gabazureus - thank you for checking my project out 😄 

I managed to reproduce your error. It occurs because no files were found to index (in the `doc_dir`).
I've implemented a fix for this, so you now should get a nice error instead of a crash.

The code picks up any `.md` files in the `doc_dir` path, you can see how in the indexing pipeline: https://github.com/larsbaunwall/bricky/blob/8437ec2676ef9e73aa0c1520d0e9fef1a7f23b26/api/pipelines/indexing.py#L53

Also note that the files need to be visible to the docker container, either by copying them into a local project folder that gets copied on build, or by mounting a volume. 

A quick start could be to put your markdown files in the `api/sources` folder and configure the `DOC_DIR` to point to `sources`

**Comment by gabriel0xdef** [comment]
Hey @larsbaunwall

Thanks for the reply!

I tried to put a .md file inside the api/sources, and specified it in DOC_DIR in .env file. But the same error persisted.

So I tried to delete all the content of the files main.py, openai.py and indexing.py.

And then tried this commands:

```
sudo docker system prune
systemctl restart docker.service
sudo docker compose down
sudo docker compose up -d
```

And then the same error persist, even with these files without any line.

Before that I put many prints inside indexing.py and main.py, and none of them printed in the log. I tried commenting out this line as well "disable_telemetry()" in main.py, to see if the following line in the log disappears: "INFO:haystack.telemetry:Telemetry has been disabled.". But it showed up anyway.

I don't know if I am doing something wrong with docker, because I am new with it.

Thanks!

**Comment by larsbaunwall** [comment]
Hi @gabriel0xdef 

From your description, I'm wondering if your docker-compose is using recent images. Deleting contents in those files should give you a whole range of other errors 😉 

Have you tried running `docker-compose up --build` in the repo root? The `--build` flag forces the images to be rebuilt.

**Comment by gabriel0xdef** [comment]
Oh yes! This command made it. Thanks!

Now I can open localhost:8080/docs
and every of my prints appeared when I run ```sudo docker compose up --build```, and got no error in the starting process.

But when I ask a question, for example "What is the capital of Brazil?", I get this error:

```
bricky-app-1  | Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
bricky-app-1  | Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
bricky-api-1  | DEBUG:haystack.pipelines.base:Running node 'Query` with input: {'root_node': 'Query', 'params': {'Generator': {'top_k': 1}, 'Retriever': {'top_k': 5}}, 'query': 'What is the capital of Brazil?', 'node_id': 'Query'}
bricky-api-1  | DEBUG:haystack.pipelines.base:Running node 'Retriever` with input: {'root_node': 'Query', 'params': {'Generator': {'top_k': 1}, 'Retriever': {'top_k': 5}}, 'query': 'What is the capital of Brazil?', 'node_id': 'Retriever'}
bricky-api-1  | ola   **<---- my print**
bricky-api-1  | tchau   **<---- my print**
bricky-api-1  | ola2   **<---- my print**
bricky-api-1  | adding nodes...   **<---- my print**
bricky-api-1  | adding markdownconverter...   **<---- my print**
bricky-api-1  | adding preprocessor...   **<---- my print**
bricky-api-1  | indexing files...
bricky-api-1  | No files found to index at path /api/sources
bricky-api-1  | Source context will be empty
bricky-api-1  | ola3   **<---- my print**
bricky-api-1  | ola4   **<---- my print**
bricky-api-1  | ola5   **<---- my print**
Calculating embeddings: 100%|██████████| 1/1 [00:01<00:00,  1.31s/it]
bricky-api-1  | DEBUG:haystack.nodes.retriever.base:Retrieved documents with IDs: []
bricky-api-1  | DEBUG:haystack.pipelines.base:Running node 'Generator` with input: {'documents': [], 'root_node': 'Query', 'params': {'Generator': {'top_k': 1}, 'Retriever': {'top_k': 5}}, 'query': 'What is the capital of Brazil?', 'node_id': 'Generator'}
**print(res) ------>** bricky-api-1  | {'answers': [], 'documents': [], 'root_node': 'Query', 'params': {'Generator': {'top_k': 1}, 'Retriever': {'top_k': 5}}, 'query': 'What is the capital of Brazil?', 'node_id': 'Generator'}   **<---- print(res)**
bricky-api-1  | INFO:     172.18.0.3:44522 - "POST /ask HTTP/1.1" 500 Internal Server Error
bricky-api-1  | ERROR:    Exception in ASGI application
bricky-api-1  | Traceback (most recent call last):
bricky-api-1  |   File "/home/appuser/./main.py", line 58, in ask
bricky-api-1  |     answer = res["answers"][0].answer
bricky-api-1  | IndexError: list index out of range
bricky-api-1  | 
bricky-api-1  | During handling of the above exception, another exception occurred:
bricky-api-1  | 
bricky-api-1  | Traceback (most recent call last):
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
bricky-api-1  |     result = await app(  # type: ignore[func-returns-value]
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
bricky-api-1  |     return await self.app(scope, receive, send)
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
bricky-api-1  |     await super().__call__(scope, receive, send)
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
bricky-api-1  |     await self.middleware_stack(scope, receive, send)
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
bricky-api-1  |     raise exc
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
bricky-api-1  |     await self.app(scope, receive, _send)
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
bricky-api-1  |     raise exc
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
bricky-api-1  |     await self.app(scope, receive, sender)
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
bricky-api-1  |     raise e
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
bricky-api-1  |     await self.app(scope, receive, send)
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
bricky-api-1  |     await route.handle(scope, receive, send)
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
bricky-api-1  |     await self.app(scope, receive, send)
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
bricky-api-1  |     response = await func(request)
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
bricky-api-1  |     raw_response = await run_endpoint_function(
bricky-api-1  |   File "/opt/venv/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
bricky-api-1  |     return await dependant.call(**values)
bricky-api-1  |   File "/home/appuser/./main.py", line 62, in ask
bricky-api-1  |     return self.ResponseModel(error=e.message)
bricky-api-1  | AttributeError: 'IndexError' object has no attribute 'message'
bricky-app-1  | SyntaxError: Unexpected token I in JSON at position 0
bricky-app-1  |     at JSON.parse (<anonymous>)
bricky-app-1  |     at packageData (node:internal/deps/undici/undici:6403:23)
bricky-app-1  |     at specConsumeBody (node:internal/deps/undici/undici:6381:14)
bricky-app-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
bricky-app-1  |     at async __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/chat.js:26:18)
bricky-app-1  |     at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:363:9)
bricky-app-1  |     at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:487:9)
bricky-app-1  |     at async Object.fn (/app/node_modules/next/dist/server/next-server.js:749:37)
bricky-app-1  |     at async Router.execute (/app/node_modules/next/dist/server/router.js:253:36)
bricky-app-1  |     at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:384:29)
```


I used a markdown file inside my api/sources with this content:

```
'''Brazil''' (; ), officially the '''Federative Republic of Brazil''' (Portuguese: ), is the largest country in both South America and Latin America. At  and with over 211 million people, Brazil is the world's fifth-largest country by area and the sixth most populous. Its capital is Brasília, and its most populous city is São Paulo. The federation is composed of the union of the 26 states and the Federal District. It is the largest country to have Portuguese as an official language and the only one in the Americas; it is also one of the most multicultural and ethnically diverse nations, due to over a century of mass immigration from around the world; as well as the most populous Roman Catholic-majority country.
```

It is possible to answer this question with the text, right?

**Comment by gabriel0xdef** [comment]
Oh yes! This command made it. Thanks!

Now I can open localhost:8080/docs
and every of my prints appeared when I run sudo docker compose up --build, and got no error in the starting process.

But when I asked a question, I got these errors:

bricky-api-1  | No files found to index at path /api/sources
bricky-api-1  | Source context will be empty
I tried "/api/sources" or "api/sources", and it give me the same.

Then I tired only "sources" and it worked!
Simply awesome!!

A doubt, is it possible to change the default language to read the DOCs contents, and the answer of Bricky to Portuguese?

If yes, what do I can change in the code?

Thank you, I would like to help you more If I can.
